WORDS = [
    {"word": "Ephemeral", "pronunciation": "ih-FEM-er-ul", "meaning": "Lasting for a very short time", "difficulty": "Hard"},
    {"word": "Ubiquitous", "pronunciation": "yoo-BIK-wi-tus", "meaning": "Present everywhere", "difficulty": "Hard"},
    {"word": "Serendipity", "pronunciation": "ser-en-DIP-i-tee", "meaning": "Finding something good without looking for it", "difficulty": "Medium"},
    {"word": "Eloquent", "pronunciation": "EL-oh-kwent", "meaning": "Fluent and persuasive in speaking", "difficulty": "Medium"},
    {"word": "Cacophony", "pronunciation": "kuh-KOF-uh-nee", "meaning": "A harsh mix of sounds", "difficulty": "Hard"},
    {"word": "Resilient", "pronunciation": "ri-ZIL-yent", "meaning": "Able to recover quickly from difficulty", "difficulty": "Easy"},
    {"word": "Ambiguous", "pronunciation": "am-BIG-yoo-us", "meaning": "Open to more than one interpretation", "difficulty": "Medium"},
    {"word": "Pragmatic", "pronunciation": "prag-MAT-ik", "meaning": "Dealing with things sensibly and realistically", "difficulty": "Medium"},
    {"word": "Nostalgic", "pronunciation": "no-STAL-jik", "meaning": "Longing for the past", "difficulty": "Easy"},
    {"word": "Meticulous", "pronunciation": "muh-TIK-yoo-lus", "meaning": "Showing great attention to detail", "difficulty": "Medium"},

{"word": "Enigmatic", "pronunciation": "en-ig-MAT-ik", "meaning": "Mysterious and difficult to understand", "difficulty": "Hard"},
    {"word": "Candid", "pronunciation": "KAN-did", "meaning": "Honest and direct", "difficulty": "Easy"},
    {"word": "Tenacious", "pronunciation": "tuh-NAY-shus", "meaning": "Holding firmly to something", "difficulty": "Medium"},
    {"word": "Fickle", "pronunciation": "FIK-uhl", "meaning": "Changing frequently, not loyal", "difficulty": "Easy"},
    {"word": "Ostentatious", "pronunciation": "os-ten-TAY-shus", "meaning": "Showy, designed to impress", "difficulty": "Hard"},
    {"word": "Prudent", "pronunciation": "PROO-dent", "meaning": "Acting with care and thought for the future", "difficulty": "Medium"},
    {"word": "Volatile", "pronunciation": "VOL-uh-tile", "meaning": "Likely to change suddenly", "difficulty": "Medium"},
    {"word": "Benevolent", "pronunciation": "buh-NEV-uh-lent", "meaning": "Kind and generous", "difficulty": "Medium"},
    {"word": "Obstinate", "pronunciation": "OB-stuh-nit", "meaning": "Stubbornly refusing to change", "difficulty": "Hard"},
    {"word": "Candor", "pronunciation": "KAN-der", "meaning": "Openness and honesty", "difficulty": "Medium"},
    {"word": "Diligent", "pronunciation": "DIL-i-jent", "meaning": "Showing care and effort in work", "difficulty": "Easy"},
    {"word": "Skeptical", "pronunciation": "SKEP-ti-kul", "meaning": "Not easily convinced, doubtful", "difficulty": "Easy"},
    {"word": "Frivolous", "pronunciation": "FRIV-uh-lus", "meaning": "Not having any serious purpose", "difficulty": "Medium"},
    {"word": "Impeccable", "pronunciation": "im-PEK-uh-bul", "meaning": "Flawless, without fault", "difficulty": "Medium"},
    {"word": "Lethargic", "pronunciation": "luh-THAR-jik", "meaning": "Lacking energy, sluggish", "difficulty": "Medium"},
    {"word": "Meticulous", "pronunciation": "muh-TIK-yoo-lus", "meaning": "Very careful and precise", "difficulty": "Medium"},
    {"word": "Quintessential", "pronunciation": "kwin-tuh-SEN-shul", "meaning": "Representing the most perfect example of something", "difficulty": "Hard"},
    {"word": "Vindictive", "pronunciation": "vin-DIK-tiv", "meaning": "Having a strong desire for revenge", "difficulty": "Hard"},
    {"word": "Amiable", "pronunciation": "AY-mee-uh-bul", "meaning": "Friendly and pleasant", "difficulty": "Easy"},
    {"word": "Astute", "pronunciation": "uh-STOOT", "meaning": "Having sharp judgment", "difficulty": "Medium"},]